version: '3.8'

services:
  # Container with .NET app
  web-api:
    image: expense-tracking-api
    build:
      context: ./ExpenseTrackingApp
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - sql-server
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=ExpenseTrackingDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;

  # Container with frontend
  frontend:
      image: expense-tracking-ui
      build:
        context: ./ExpenseTrackingAppUI
        dockerfile: Dockerfile
      ports:
        - "3000:80"

  # Container with SSMS database
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}